### ISSUE TITLE
Installation error: Module not found ../build/Release/bson

### ISSUE THREAD

**Issue by dewwwald** [leo7568/generator-keystone-react#8]
Node Version: v6.9.1
actual node module dir: [project dir]/node_modules/bson/build/Release/nodec

Could this issue be caused by the installation with out the proper versions?

Here is the full error log.

```
Error: failed to connect to [localhost:27017]
    at .<anonymous> (/Users/dewald/work/sites/sharemate/node_modules/mongodb/lib/mongodb/connection/server.js:556:25)
    at emitThree (events.js:116:13)
    at emit (events.js:194:7)
    at .<anonymous> (/Users/dewald/work/sites/sharemate/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/Users/dewald/work/sites/sharemate/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/Users/dewald/work/sites/sharemate/node_modules/keystone/lib/core/mount.js:630
			throw new Error('KeystoneJS (' + keystone.get('name') + ') failed to start');
```

Any direction in how I can go about solving this issue?

I am also on mac.

**Comment by eltel** [comment]
Same issue here

**Comment by eltel** [comment]
Instructions here!!

https://github.com/keystonejs/generator-keystone-react/issues/7

**Comment by dewwwald** [comment]
@eltel You are Power! Thanks! 

Are you referring to the mongo permissions part? 

I don't think version conflicts should be solved by editing node modules.

**Comment by eltel** [comment]
No...the missing bson file - worked my end. Mongo DB was the other reason it wasn't initiating.

You may be right on the node modules part - but for now it's working.

**Comment by robksawyer** [comment]
I was able to fix the problem by simply running `yarn upgrade keystone`.
